AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda consumer de SQS em Go

Globals:
  Function:
    Environment:
      Variables:
        MONGO_URL: !Sub "{{resolve:ssm-secure:/processor/MONGO_URL}}"

Resources:
  ChatUpdatesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: chat-updates-queue

  ChatConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ChatConsumer
      Handler: main
      Runtime: go1.x
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          LOG_LEVEL: info
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ChatUpdatesQueue.Arn
            BatchSize: 1
